# Generated by Django 3.1.12 on 2025-02-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
