# Generated by Django 3.1.12 on 2025-02-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='shipper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
